import { Router } from "express";
import { createBlog, deleteBlog, getPublicBlog, listAdminBlogs, listFeaturedBlogs, listPublicBlogs, updateBlog, updateFeaturedBlog } from "../controllers/blogController.js";
import { requireAdmin } from "../middleware/requireAdmin.js";
export const publicBlogRouter = Router();
export const adminBlogRouter = Router();
publicBlogRouter.get("/", listPublicBlogs);
publicBlogRouter.get("/featured", listFeaturedBlogs);
publicBlogRouter.get("/:slug", getPublicBlog);
adminBlogRouter.get("/blogs", requireAdmin, listAdminBlogs);
adminBlogRouter.post("/blogs", requireAdmin, createBlog);
adminBlogRouter.put("/blogs/:id", requireAdmin, updateBlog);
adminBlogRouter.patch("/blogs/:id/featured", requireAdmin, updateFeaturedBlog);
adminBlogRouter.delete("/blogs/:id", requireAdmin, deleteBlog);
