const entries = [
  ["private-car-insurance", "Private Car Insurance"],
  ["two-wheeler-insurance", "Two-Wheeler Insurance"],
  ["electric-vehicle-insurance", "Electric Vehicle (EV) Insurance"],
  ["commercial-vehicle-fleet-insurance", "Commercial Vehicle & Fleet"],
  ["health-insurance", "Health Insurance"],
  ["critical-illness-insurance", "Critical Illness Insurance"],
  ["travel-insurance", "Travel Insurance"],
  ["super-top-up-insurance", "Super Top-Up Insurance"],
  ["term-life-insurance", "Term Life Insurance"],
  ["keyman-insurance", "Keyman Insurance"],
  ["employer-employee-insurance", "Employer Employee Insurance"],
  ["retirement-pension-plans", "Retirement / Pension Plans"],
  ["high-net-worth-solutions", "High Net-Worth Solutions"],
  ["private-client-group", "Private Client Group"],
  ["global-health-covers", "Global Health Covers"],
  ["industrial-all-risk-insurance", "Industrial All Risk (IAR)"],
  ["property-all-risk-insurance", "Property All Risk (PAR)"],
  ["small-commercial-insurance", "Small Commercial"],
  ["miscellaneous-insurance", "Miscellaneous"],
  ["contractors-all-risk-insurance", "Contractors All Risk (CAR)"],
  ["erection-all-risk-insurance", "Erection All Risk (EAR)"],
  ["contractors-plant-machinery-insurance", "Contractors Plant & Machinery"],
  ["machinery-breakdown-insurance", "Machinery Breakdown"],
  ["electronic-equipment-insurance", "Electronic Equipment"],
  ["group-health-insurance", "Group Health Insurance"],
  ["group-term-life-insurance", "Group Term Life Insurance"],
  ["group-personal-accident-insurance", "Group Personal Accident"],
  ["group-gratuity-superannuation", "Group Gratuity & Superannuation"],
  ["surety-bonds", "Surety Bonds"],
  ["trade-credit-insurance", "Trade Credit Insurance"],
  ["marine-hull-aviation-insurance", "Marine Hull & Aviation"],
  ["cyber-crime-insurance", "Cyber & Crime"],
  ["commercial-general-liability-insurance", "Commercial General Liability"],
  ["professional-indemnity-insurance", "Professional Indemnity"],
  ["directors-officers-liability-insurance", "Directors & Officers Liability"],
  ["employers-liability-insurance", "Employers Liability"],
  ["corporate-cyber-insurance", "Corporate Cyber Insurance"],
  ["personal-cyber-insurance", "Personal Cyber Insurance"],
  ["group-cyber-insurance", "Group Cyber Insurance"],
  ["affinity-partnership-insurance", "Affinity & Partnership Insurance"],
  ["warranty-indemnity-insurance", "Warranty & Indemnity"],
  ["representations-warranties-insurance", "Representations & Warranties"],
  ["tax-liability-insurance", "Tax Liability Insurance"],
  ["contingent-liability-insurance", "Contingent Liability Insurance"],
  ["specific-litigation-risk", "Specific Litigation Risk"],
  ["transactional-risk-covers", "Transactional Risk Covers"],
];

export const servicePages = new Map(entries);

export function isServicePage(page) {
  return typeof page === "string" && servicePages.has(page);
}
